servigcontrol/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('services/', views.services, name="services"),
    path('contact/', views.contact, name="contact"),
    path('crear_usuario/', views.crear_usuario, name= 'crear_usuario'),
    path('turnos/', views.turnos, name="turnos"),
    path('turnos_completos/', views.turnos_completos, name="turnos_completos"),
    path('turno/crear/', views.crear_turno, name="crear_turno"),
    path('turno/<int:turno_id>/', views.datalle_turno, name="detalle_turno"),
    path('turno/<int:turno_id>/eliminar/', views.eliminar_turno, name="eliminar_turno"),
    path('turno/<int:turno_id>/completar/', views.completar_turno, name="completar_turno"),
]

servigcontrol/servigcontrol/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('iniciar_sesion/', views.iniciar_sesion, name= 'iniciar_sesion'),
    path('principal/', views.principal, name= 'principal'),
    path('cerrar_sesion/', views.cerrar_sesion, name= 'cerrar_sesion'),
]

servigcontrol/myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Turno(models.Model):
    title = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    fecha_completada = models.DateTimeField(null = True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title + '- Usuario: ' + self.user.username
    

servigcontrol/myapp/forms.py
from django.forms import ModelForm
from .models import Turno

class crear_turno_form(ModelForm):
    class Meta:
        model = Turno
        fields = ['title', 'descripcion']

servigcontrol/myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .forms import crear_turno_form
from .models import Turno
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'myapp/index.html')
    
def about(request):
    return render(request, 'myapp/about.html')
    
def services(request):
    return render(request, 'myapp/services.html')
    
def contact(request):
    return render(request, 'myapp/contact.html')

def iniciar_sesion(request):
    if request.method == 'GET':
        return render(request, 'myapp/iniciar_sesion.html',{
            'form' : AuthenticationForm
        })
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'myapp/iniciar_sesion.html',{
                'form' : AuthenticationForm,
                'error' : "Usuario o Contraseña incorrecta"
            })
        else:
            login(request, user)
            return redirect('principal')
        
@login_required        
def principal(request):
    return render(request, 'myapp/principal.html')

@login_required        
def cerrar_sesion(request):
    logout(request)
    return redirect('index')
    
@login_required        
def crear_usuario(request):
    if request.method == 'GET':
        return render(request, 'myapp/crear_usuario.html',{
            'form' : UserCreationForm
        })
    else:
        try:
            user = User.objects.create_user(username=request.POST['username'], email=request.POST['email'], password=request.POST['password'])
            user.save()
            login(request, user)
            return redirect('principal')
        except IntegrityError:
            return render(request, 'myapp/crear_usuario.html',{
                'form' : UserCreationForm,
                "error" : 'El usuario ya existe'
            })
                
@login_required        
def turnos(request):
    turnos = Turno.objects.all()
    return render(request, 'myapp/turnos/turnos.html',{
        'turnos' : turnos
    })

@login_required    
def turnos_completos(request):
    turnos = Turno.objects.filter(fecha_completada__isnull=False).order_by('-fecha_completada')
    return render(request, 'myapp/turnos/turnos.html',{
        'turnos' : turnos
    })          

@login_required
def crear_turno(request):
    if request.method == 'GET':
        return render(request, 'myapp/turnos/crear_turno.html', {
            'form' : crear_turno_form
        })
    else:
        try:
            form = crear_turno_form(request.POST)
            nuevo_turno = form.save(commit=False)
            nuevo_turno.user = request.user
            nuevo_turno.save()
            return redirect('turnos')
        except ValueError:
            return render(request, 'myapp/turnos/crear_turno.html', {
                'form' : crear_turno_form,
                'error' : 'Ingresa datos validos'
            })
            
@login_required            
def datalle_turno(request, turno_id):
    if request.method == 'GET':
        turno = get_object_or_404(Turno, pk=turno_id)
        form = crear_turno_form(instance=turno)
        return render(request, 'myapp/turnos/detalle_turno.html',{
            'turno' : turno,
            'form' : form
        })
    else:
        try:
            turno = get_object_or_404(Turno, pk=turno_id)
            form = crear_turno_form(request.POST, instance=turno)
            form.save()
            return redirect('turnos')
        except ValueError:
            return render(request, 'myapp/turnos/detalle_turno.html',{
            'turno' : turno,
            'form' : form,
            'error' : "Error al actualizar"
        })
            
@login_required    
def eliminar_turno(request, turno_id):
    turno = get_object_or_404(Turno, pk=turno_id)
    if request.method == 'POST':
        turno.delete()
        return redirect('turnos')
    
@login_required                    
def completar_turno(request, turno_id):
    turno = get_object_or_404(Turno, pk=turno_id)
    if request.method == 'POST':
        turno.fecha_completada = timezone.now()
        turno.save()
        return redirect('turnos')
    

servigcontrol/myapp/templates/layouts/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="utf-8">
        <title>Servigcontrol S.A.S</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600&family=Roboto&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>

        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        <!-- Topbar Start -->
        <div class="container-fluid bg-primary px-5 d-none d-lg-block">
            <div class="row gx-0">
                <div class="col-lg-8 text-center text-lg-start mb-2 mb-lg-0">
                    <div class="d-inline-flex align-items-center" style="height: 45px;">
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="https://x.com/"><i class="fab fa-twitter fw-normal"></i></a>
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="https://www.facebook.com/"><i class="fab fa-facebook-f fw-normal"></i></a>
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="https://www.linkedin.com/"><i class="fab fa-linkedin-in fw-normal"></i></a>
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="https://www.instagram.com/"><i class="fab fa-instagram fw-normal"></i></a>
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle" href="https://www.youtube.com/"><i class="fab fa-youtube fw-normal"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 text-center text-lg-end">
                    <div class="d-inline-flex align-items-center" style="height: 45px;">
                        <a href="/iniciar_sesion"><small class="me-3 text-light"><i class="fa fa-sign-in-alt me-2"></i>iniciar Sesión</small></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Topbar End -->
        
        <!-- Navbar & Hero Start -->
        <div class="container-fluid position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
                <a href="" class="navbar-brand p-0">
                    <h1 class="m-0 text-primary"><i class="fa fa-map-marker-alt me-3"></i>Servigcontrol</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 ">
                        <a href="/" class="nav-item nav-link active">Inicio</a>
                        <a href="/about" class="nav-item nav-link active">Acerda de</a>
                        <a href="/services" class="nav-item nav-link active">Servicios</a>
                        <a href="/contact" class="nav-item nav-link active">Contacto</a>
                    </div>
                </div>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
        <!-- Navbar & Hero End -->

        <!-- Footer Start -->
        <div class="container-fluid footer py-5 bg-dark text-white">
            <div class="container py-5">
                <div class="row justify-content-center g-5">
                    <div class="col-md-6 col-lg-6 col-xl-3 text-center">
                        <div class="footer-item d-flex flex-column align-items-center">
                            <h4 class="mb-4">Get In Touch</h4>
                            <a href=""><i class="fas fa-home me-2"></i> 123 Street, New York, USA</a>
                            <a href=""><i class="fas fa-envelope me-2"></i> info@example.com</a>
                            <a href=""><i class="fas fa-phone me-2"></i> +012 345 67890</a>
                            <a href="" class="mb-3"><i class="fas fa-print me-2"></i> +012 345 67890</a>
                            <div class="d-flex align-items-center justify-content-center">
                                <i class="fas fa-share fa-2x me-2"></i>
                                <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://x.com/"><i class="fab fa-twitter"></i></a>
                                <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                                <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.linkedin.com/"><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Copyright Start -->
        <div class="container-fluid copyright text-body py-4">
            <div class="container">
                <div class="row g-4 align-items-center">
                    <div class="col-md-6 text-center text-md-end mb-md-0">
                        <i class="fas fa-copyright me-2"></i><a class="text-white" href="#">Your Site Name</a>, All right reserved.
                    </div>
                    <div class="col-md-6 text-center text-md-start">
                        <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->
                        <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->
                        <!--/*** you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". ***/-->
                        Designed By <a class="text-white" href="https://htmlcodex.com">HTML Codex</a> Distributed By <a href="https://themewagon.com">ThemeWagon</a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Copyright End -->

        <!-- Back to Top -->
        <a href="#" class="btn btn-primary btn-primary-outline-0 btn-md-square back-to-top"><i class="fa fa-arrow-up"></i></a>   

        
        <!-- JavaScript Libraries -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/lightbox/js/lightbox.min.js"></script>
        

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>

</html>

servigcontrol/myapp/templates/layouts/layout_2.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="utf-8">
        <title>Servigcontrol S.A.S</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600&family=Roboto&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>

        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        <!-- Topbar Start -->
        <div class="container-fluid bg-primary px-5 d-none d-lg-block">
            <div class="row gx-0">
                <div class="col-lg-8 text-center text-lg-start mb-2 mb-lg-0">
                    <div class="d-inline-flex align-items-center" style="height: 45px;">
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="https://x.com/"><i class="fab fa-twitter fw-normal"></i></a>
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="https://www.facebook.com/"><i class="fab fa-facebook-f fw-normal"></i></a>
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="https://www.linkedin.com/"><i class="fab fa-linkedin-in fw-normal"></i></a>
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle me-2" href="https://www.instagram.com/"><i class="fab fa-instagram fw-normal"></i></a>
                        <a class="btn btn-sm btn-outline-light btn-sm-square rounded-circle" href="https://www.youtube.com/"><i class="fab fa-youtube fw-normal"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Topbar End -->
        
        <!-- Navbar & Hero Start -->
        <div class="container-fluid position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
                <a href="" class="navbar-brand p-0">
                    <h1 class="m-0 text-primary"><i class="fa fa-map-marker-alt me-3"></i>Servigcontrol</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
        <!-- Navbar & Hero End -->

        <!-- Footer Start -->
<div class="container-fluid footer py-5 bg-dark text-white">
    <div class="container py-5">
        <div class="row justify-content-center g-5">
            <div class="col-md-6 col-lg-6 col-xl-3 text-center">
                <div class="footer-item d-flex flex-column align-items-center">
                    <h4 class="mb-4">Get In Touch</h4>
                    <a href=""><i class="fas fa-home me-2"></i> 123 Street, New York, USA</a>
                    <a href=""><i class="fas fa-envelope me-2"></i> info@example.com</a>
                    <a href=""><i class="fas fa-phone me-2"></i> +012 345 67890</a>
                    <a href="" class="mb-3"><i class="fas fa-print me-2"></i> +012 345 67890</a>
                    <div class="d-flex align-items-center justify-content-center">
                        <i class="fas fa-share fa-2x me-2"></i>
                        <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://x.com/"><i class="fab fa-twitter"></i></a>
                        <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                        <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.linkedin.com/"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

        
        <!-- Copyright Start -->
        <div class="container-fluid copyright text-body py-4">
            <div class="container">
                <div class="row g-4 align-items-center">
                    <div class="col-md-6 text-center text-md-end mb-md-0">
                        <i class="fas fa-copyright me-2"></i><a class="text-white" href="#">Your Site Name</a>, All right reserved.
                    </div>
                    <div class="col-md-6 text-center text-md-start">
                        <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->
                        <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->
                        <!--/*** you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". ***/-->
                        Designed By <a class="text-white" href="https://htmlcodex.com">HTML Codex</a> Distributed By <a href="https://themewagon.com">ThemeWagon</a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Copyright End -->

        <!-- JavaScript Libraries -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/lightbox/js/lightbox.min.js"></script>
        

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>

</html>

servigcontrol/myapp/templates/layouts/layout_3.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
    <head>
        <meta charset="utf-8">
        <title>Servigcontrol S.A.S</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600&family=Roboto&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>

        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        
        
        {% block content %}
        {% endblock %}


        <!-- Carousel Start -->
<div class="carousel-header">
    <div id="carouselId" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img src="{% static 'img/logo-Servigcontrol.jpg' %}" class="img-fluid" alt="Image">
                <div class="carousel-caption">
                    <div class="p-3" style="max-width: 900px;">
                        <h4 class="text-white text-uppercase fw-bold mb-4" style="letter-spacing: 3px;">Explore The World</h4>
                        <h1 class="display-2 text-capitalize text-white mb-4">Let's The World Together!</h1>
                        <p class="mb-5 fs-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Carousel End -->


        <!-- Footer Start -->
        <div class="container-fluid footer py-5 bg-dark text-white">
            <div class="container py-5">
                <div class="row justify-content-center g-5">
                    <div class="col-md-6 col-lg-6 col-xl-3 text-center">
                        <div class="footer-item d-flex flex-column align-items-center">
                            <h4 class="mb-4">Get In Touch</h4>
                            <a href=""><i class="fas fa-home me-2"></i> 123 Street, New York, USA</a>
                            <a href=""><i class="fas fa-envelope me-2"></i> info@example.com</a>
                            <a href=""><i class="fas fa-phone me-2"></i> +012 345 67890</a>
                            <a href="" class="mb-3"><i class="fas fa-print me-2"></i> +012 345 67890</a>
                            <div class="d-flex align-items-center justify-content-center">
                                <i class="fas fa-share fa-2x me-2"></i>
                                <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://x.com/"><i class="fab fa-twitter"></i></a>
                                <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                                <a class="btn-square btn btn-primary rounded-circle mx-1" href="https://www.linkedin.com/"><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Copyright Start -->
        <div class="container-fluid copyright text-body py-4">
            <div class="container">
                <div class="row g-4 align-items-center">
                    <div class="col-md-6 text-center text-md-end mb-md-0">
                        <i class="fas fa-copyright me-2"></i><a class="text-white" href="#">Your Site Name</a>, All right reserved.
                    </div>
                    <div class="col-md-6 text-center text-md-start">
                        <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->
                        <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->
                        <!--/*** you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". ***/-->
                        Designed By <a class="text-white" href="https://htmlcodex.com">HTML Codex</a> Distributed By <a href="https://themewagon.com">ThemeWagon</a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Copyright End -->

        <!-- JavaScript Libraries -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/lightbox/js/lightbox.min.js"></script>
        

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>

</html>

servigcontrol/myapp/templates/myapp/turnos/detalle_turno.html
{% extends 'layouts/layout_2.html' %}

{% block content %}

<form class="container-fluid" method="POST">
    {% csrf_token %}
    {{error}}
    <div class="container-fluid">
        <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
            <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
                <div class="bg-dark rounded p-4 p-sm-5 my-4 mx-3">
                    <div class="d-flex align-items-center justify-content-between mb-3">
                            <h3 class="text-primary text-center"><i class="fa fa-user-edit me-2"></i>{{turno.title}}</h3>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" required id="id_title" name="title" value="{{ turno.title }}">
                        <label for="id_title">Turno</label>
                    </div>
                    <div class="form-floating mb-4">
                        <input type="text" class="form-control" required id="id_descripcion" name="descripcion" value="{{ turno.descripcion }}">
                        <label for="id_descripcion">Descripción</label>
                    </div>

                    <form method="POST">
                        <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Actualizar</button>
                    </form>
                    <form action="{% url 'completar_turno' turno.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Asistencia</button>
                    </form>
                    <form action="{% url 'eliminar_turno' turno.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary py-3 w-100 mb-4">Eliminar</button>
                    </form>
                    <p class="text-center mb-0">Volver: <a href="/turnos">Turnos</a></p>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}